FROM eclipse-temurin:21.0.11_10-jdk@sha256:1eeacc8c295ed4805f6ffead2417b1936aad296b02ea9e56b457230befc9e98d
COPY build/libs/backend.jar /app/backend.jar
ENTRYPOINT ["java", "-jar", "/app/backend.jar"]
